[2023-06-13T15:00:51.936+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: ETL_psql_redshift_dag.ETL_s3 manual__2023-06-13T14:55:56.120360+00:00 [queued]>
[2023-06-13T15:00:51.946+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: ETL_psql_redshift_dag.ETL_s3 manual__2023-06-13T14:55:56.120360+00:00 [queued]>
[2023-06-13T15:00:51.947+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-06-13T15:00:51.948+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 3
[2023-06-13T15:00:51.948+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-06-13T15:00:51.957+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): ETL_s3> on 2023-06-13 14:55:56.120360+00:00
[2023-06-13T15:00:51.962+0000] {standard_task_runner.py:55} INFO - Started process 537 to run task
[2023-06-13T15:00:51.966+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'ETL_psql_redshift_dag', 'ETL_s3', 'manual__2023-06-13T14:55:56.120360+00:00', '--job-id', '26', '--raw', '--subdir', 'DAGS_FOLDER/dags_setup.py', '--cfg-path', '/tmp/tmpxq9fgu71']
[2023-06-13T15:00:51.968+0000] {standard_task_runner.py:83} INFO - Job 26: Subtask ETL_s3
[2023-06-13T15:00:52.018+0000] {task_command.py:388} INFO - Running <TaskInstance: ETL_psql_redshift_dag.ETL_s3 manual__2023-06-13T14:55:56.120360+00:00 [running]> on host 63f0fed3274d
[2023-06-13T15:00:52.071+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=vupham
AIRFLOW_CTX_DAG_ID=ETL_psql_redshift_dag
AIRFLOW_CTX_TASK_ID=ETL_s3
AIRFLOW_CTX_EXECUTION_DATE=2023-06-13T14:55:56.120360+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-06-13T14:55:56.120360+00:00
[2023-06-13T15:00:52.073+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/ETL_redshift/ETL_psql_s3.py", line 146, in ETL_s3
    Extract_from_postgreSQL(df_dict);
  File "/opt/airflow/dags/ETL_redshift/ETL_psql_s3.py", line 26, in Extract_from_postgreSQL
    conn = Setup_psql_connection();
  File "/opt/airflow/dags/ETL_redshift/ETL_psql_s3.py", line 19, in Setup_psql_connection
    conn = psycopg2.connect(**connect_params);
  File "/home/airflow/.local/lib/python3.7/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 5432 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?

[2023-06-13T15:00:52.082+0000] {taskinstance.py:1323} INFO - Marking task as UP_FOR_RETRY. dag_id=ETL_psql_redshift_dag, task_id=ETL_s3, execution_date=20230613T145556, start_date=20230613T150051, end_date=20230613T150052
[2023-06-13T15:00:52.090+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 26 for task ETL_s3 (connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 5432 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?
; 537)
[2023-06-13T15:00:52.138+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-06-13T15:00:52.156+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
